import {
    FaBullseye,
    FaUserCheck,
    FaClock,
    FaCheckCircle,
    FaFileExcel,
    FaHandHoldingUsd,
    FaUsers,
    FaGlobeAmericas,
} from 'react-icons/fa';
import CompanyMidBanner from './CompanyMidBanner';

const BENEFITS = [
    {
        Icon: FaBullseye,
        title: 'Targeted Data, Not Massive Databases',
        description:
            'Receive only the contacts that match your Ideal Customer Profile (ICP) based on industry, job title, location, company size, revenue, technologies, and more.',
    },
    {
        Icon: FaUserCheck,
        title: 'Human-Verified Research',
        description:
            'Every contact is researched and verified by our data specialists to ensure relevance and accuracy—not just generated by software.',
    },
    {
        Icon: FaClock,
        title: 'Save Hours of Manual Prospecting',
        description:
            'No more searching thousands of records to find the right people. We do the research so your sales team can focus on closing deals.',
    },
    {
        Icon: FaCheckCircle,
        title: 'High-Accuracy Business Contacts',
        description:
            'Each list goes through a multi-step verification process to improve deliverability and reduce bounced emails.',
    },
    {
        Icon: FaFileExcel,
        title: 'Fresh & Ready-to-Use Data',
        description:
            'Receive clean, organized, and up-to-date business contacts in Excel or CSV format, ready for your CRM or email campaigns.',
    },
    {
        Icon: FaHandHoldingUsd,
        title: 'Pay Only for What You Need',
        description:
            'No expensive annual subscriptions. Whether you need 50, 500, or 5,000 contacts, you only pay for the data you require.',
    },
    {
        Icon: FaUsers,
        title: 'Built for Sales & Marketing Teams',
        description:
            'Perfect for cold email campaigns, lead generation, Account-Based Marketing (ABM), CRM enrichment, and outbound sales.',
    },
    {
        Icon: FaGlobeAmericas,
        title: 'Global Business Coverage',
        description:
            'Access verified decision-makers across industries and countries from one trusted data partner.',
    },
];

const COMPARISON_HEADINGS = ['Traditional Data Platforms', 'Database Providers'];

const COMPARISON_ROWS = [
    {
        traditional: 'Pay for expensive monthly or annual subscriptions',
        ours: 'Pay only for the contacts you need',
    },
    {
        traditional: 'Search and filter contacts yourself',
        ours: 'We research and build the list for you',
    },
    {
        traditional: 'Spend hours finding the right decision-makers',
        ours: 'Ready-to-use targeted database delivered',
    },
    {
        traditional: 'Verify exported contacts yourself',
        ours: 'Human-verified business contacts',
    },
    {
        traditional: 'Large databases with many irrelevant records',
        ours: 'Custom-built lists based on your exact requirements',
    },
    {
        traditional: 'Requires time and training',
        ours: 'Simple, fast, and hassle-free',
    },
];

const YOU_TELL_US = [
    'Industry',
    'Job Title',
    'Location',
    'Company Size',
    'Revenue',
    'Technologies Used',
    'Any custom requirements',
];

const WE_DELIVER = [
    'Human-verified business contacts',
    'High-accuracy email addresses',
    'Direct decision-makers',
    'Ready-to-use Excel or CSV files',
    'Fast turnaround',
];

const EXAMPLES = [
    {
        question: 'Need 50 CEOs from Manufacturing companies in Germany?',
        answer: "We'll research, verify, and deliver the list.",
    },
    {
        question: 'Need 200 Marketing Directors from SaaS companies in the USA?',
        answer: "We'll build a targeted database that's ready for your outreach campaign.",
    },
];

function SectionShell({ children, className = '' }) {
    return (
        <section
            className={`overflow-hidden rounded-[20px] bg-white shadow-[0px_2px_6px_rgba(13,10,44,0.1)] ${className}`}
        >
            {children}
        </section>
    );
}

function SectionHeader({ eyebrow, title, description }) {
    return (
        <div className="max-w-4xl">
            {eyebrow ? (
                <span className="inline-flex rounded-full bg-blue-600 px-4 py-2 text-[12px] font-medium text-white md:text-[14px]">
                    {eyebrow}
                </span>
            ) : null}
            <h2
                className={`text-[18px] font-regular text-[#111827] md:text-[28px] ${
                    eyebrow ? 'mt-3' : ''
                }`}
            >
                {title}
            </h2>
            {description ? (
                <p className="mt-4 text-[14px] leading-[1.75] text-[#4B5563] md:text-[16px]">
                    {description}
                </p>
            ) : null}
        </div>
    );
}

function BenefitCard({ Icon, title, description }) {
    return (
        <div className="rounded-[20px] bg-[#F7F7F8] p-6 transition-shadow hover:shadow-[0px_8px_24px_rgba(13,10,44,0.08)]">
            <div className="mb-3 border-b border-[#D0D0D099] pb-5">
                <div className="flex h-[52px] w-[52px] items-center justify-center rounded-[14px] bg-white text-[#1798FF] shadow-[0px_2px_6px_rgba(13,10,44,0.06)]">
                    <Icon className="text-[26px]" aria-hidden="true" />
                </div>
            </div>
            <h3 className="text-[16px] font-medium text-[#111827] md:text-[18px]">{title}</h3>
            <p className="mt-2 text-[14px] leading-[1.7] text-[#51525C] md:text-[15px]">{description}</p>
        </div>
    );
}

function ComparisonTable() {
    return (
        <div className="overflow-x-auto">
            <table
                className="w-full border-separate border-spacing-0 overflow-hidden rounded-xl shadow-sm"
                style={{ border: '1px solid #BADCFF' }}
            >
                <thead>
                    <tr className="bg-[#E6F0FF]">
                        {COMPARISON_HEADINGS.map((heading, i) => (
                            <th
                                key={heading}
                                className={`p-4 text-[15px] font-semibold text-[#111827] md:text-[16px] ${
                                    i === 0
                                        ? 'w-1/2 border-r border-[#BADCFF] text-left'
                                        : 'text-left'
                                } border-b border-[#BADCFF]`}
                            >
                                {heading}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {COMPARISON_ROWS.map((row, i) => (
                        <tr key={row.traditional} className="transition-colors hover:bg-gray-50">
                            <td
                                className={`border-r border-[#E6F0FF] p-4 text-left text-[14px] leading-relaxed text-[#4B5563] md:text-[15px] ${
                                    i !== COMPARISON_ROWS.length - 1 ? 'border-b border-[#E6F0FF]' : ''
                                }`}
                            >
                                {row.traditional}
                            </td>
                            <td
                                className={`p-4 text-left text-[14px] font-medium leading-relaxed text-[#111827] md:text-[15px] ${
                                    i !== COMPARISON_ROWS.length - 1 ? 'border-b border-[#E6F0FF]' : ''
                                }`}
                            >
                                {row.ours}
                            </td>
                        </tr>
                    ))}
                </tbody>
            </table>
        </div>
    );
}

function ListColumn({ title, items, accent = false }) {
    return (
        <div className="rounded-[16px] bg-[#F9FAFB] p-6 md:p-7">
            <div className="flex items-center gap-3">
                <span
                    className={`flex h-9 w-9 items-center justify-center rounded-[10px] text-[14px] font-semibold ${
                        accent
                            ? 'bg-[#E8F4FF] text-[#1798FF]'
                            : 'bg-[#EEF2F8] text-[#6B7280]'
                    }`}
                >
                    {accent ? '02' : '01'}
                </span>
                <h3
                    className={`text-[17px] font-semibold md:text-[20px] ${
                        accent ? 'text-[#1798FF]' : 'text-[#111827]'
                    }`}
                >
                    {title}
                </h3>
            </div>
            <ul className="mt-5 space-y-3.5">
                {items.map((item) => (
                    <li
                        key={item}
                        className="flex items-start gap-3 text-[14px] text-[#374151] md:text-[15px]"
                    >
                        <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[#1798FF]" />
                        {item}
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default function CompanyWhyChoose() {
    return (
        <div className="space-y-6">
            <SectionShell>
                <div className="px-5 py-6 md:px-8 md:py-8">
                    <div className="rounded-[16px] bg-[#F9FAFB] px-5 py-6 md:px-7 md:py-7">
                        <SectionHeader
                            eyebrow="Why Choose Database Providers?"
                            title="Stop Searching. Start Selling."
                            description="Most businesses don't need access to millions of contacts—they need the right decision-makers for their next campaign. Instead of spending hours searching, filtering, and verifying contacts, simply share your requirements and we'll deliver a ready-to-use, human-verified database."
                        />
                    </div>
                </div>
            </SectionShell>

            <SectionShell>
                <div className="px-5 py-6 md:px-8 md:py-8">
                    <SectionHeader title="Why Businesses Choose Us" />
                    <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                        {BENEFITS.map((benefit) => (
                            <BenefitCard key={benefit.title} {...benefit} />
                        ))}
                    </div>
                </div>
            </SectionShell>

            <SectionShell>
                <div className="px-5 py-6 md:px-8 md:py-8">
                    <SectionHeader title="Why Buy Custom Data Instead of a Subscription?" />
                    <div className="mt-6">
                        <ComparisonTable />
                    </div>
                </div>
            </SectionShell>

            <SectionShell>
                <div className="px-5 py-6 md:px-8 md:py-8">
                    <SectionHeader title="How It Works" />
                    <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">
                        <ListColumn title="You Tell Us" items={YOU_TELL_US} />
                        <ListColumn title="We Deliver" items={WE_DELIVER} accent />
                    </div>
                </div>
            </SectionShell>

            <SectionShell>
                <div className="px-5 py-6 md:px-8 md:py-8">
                    <SectionHeader title="Example" />
                    <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">
                        {EXAMPLES.map((example) => (
                            <div
                                key={example.question}
                                className="overflow-hidden rounded-[16px] bg-[#F0F7FF] p-5 md:p-6"
                                style={{ borderLeft: '4px solid #007AFF' }}
                            >
                                <p className="text-[15px] font-semibold text-[#111827] md:text-[16px]">
                                    {example.question}
                                </p>
                                <p className="mt-2 text-[14px] leading-[1.7] text-[#00000099] md:text-[15px]">
                                    {example.answer}
                                </p>
                            </div>
                        ))}
                    </div>
                </div>
            </SectionShell>

            <CompanyMidBanner
                title="You Focus on Closing Deals. We'll Handle the Prospect Research."
                description="Human-Verified • Targeted • Accurate • Fast • Affordable"
                buttonLabel="Get Started"
            />
        </div>
    );
}
