import CompanyMidBanner from './CompanyMidBanner';

const BENEFITS = [
    {
        icon: '🎯',
        title: 'Targeted Data, Not Massive Databases',
        description:
            'Receive only the contacts that match your Ideal Customer Profile (ICP) based on industry, job title, location, company size, revenue, technologies, and more.',
    },
    {
        icon: '👨‍💼',
        title: 'Human-Verified Research',
        description:
            'Every contact is researched and verified by our data specialists to ensure relevance and accuracy—not just generated by software.',
    },
    {
        icon: '⏱️',
        title: 'Save Hours of Manual Prospecting',
        description:
            'No more searching thousands of records to find the right people. We do the research so your sales team can focus on closing deals.',
    },
    {
        icon: '✅',
        title: 'High-Accuracy Business Contacts',
        description:
            'Each list goes through a multi-step verification process to improve deliverability and reduce bounced emails.',
    },
    {
        icon: '📊',
        title: 'Fresh & Ready-to-Use Data',
        description:
            'Receive clean, organized, and up-to-date business contacts in Excel or CSV format, ready for your CRM or email campaigns.',
    },
    {
        icon: '💰',
        title: 'Pay Only for What You Need',
        description:
            'No expensive annual subscriptions. Whether you need 50, 500, or 5,000 contacts, you only pay for the data you require.',
    },
    {
        icon: '🚀',
        title: 'Built for Sales & Marketing Teams',
        description:
            'Perfect for cold email campaigns, lead generation, Account-Based Marketing (ABM), CRM enrichment, and outbound sales.',
    },
    {
        icon: '🌍',
        title: 'Global Business Coverage',
        description:
            'Access verified decision-makers across industries and countries from one trusted data partner.',
    },
];

const COMPARISON_ROWS = [
    {
        traditional: 'Pay for expensive monthly or annual subscriptions',
        ours: 'Pay only for the contacts you need',
    },
    {
        traditional: 'Search and filter contacts yourself',
        ours: 'We research and build the list for you',
    },
    {
        traditional: 'Spend hours finding the right decision-makers',
        ours: 'Ready-to-use targeted database delivered',
    },
    {
        traditional: 'Verify exported contacts yourself',
        ours: 'Human-verified business contacts',
    },
    {
        traditional: 'Large databases with many irrelevant records',
        ours: 'Custom-built lists based on your exact requirements',
    },
    {
        traditional: 'Requires time and training',
        ours: 'Simple, fast, and hassle-free',
    },
];

const YOU_TELL_US = [
    'Industry',
    'Job Title',
    'Location',
    'Company Size',
    'Revenue',
    'Technologies Used',
    'Any custom requirements',
];

const WE_DELIVER = [
    'Human-verified business contacts',
    'High-accuracy email addresses',
    'Direct decision-makers',
    'Ready-to-use Excel or CSV files',
    'Fast turnaround',
];

const EXAMPLES = [
    {
        question: 'Need 50 CEOs from Manufacturing companies in Germany?',
        answer: "We'll research, verify, and deliver the list.",
    },
    {
        question: 'Need 200 Marketing Directors from SaaS companies in the USA?',
        answer: "We'll build a targeted database that's ready for your outreach campaign.",
    },
];

function SectionCard({ children, className = '' }) {
    return (
        <section
            className={`rounded-[24px] border border-[#E8EDF5] bg-white p-6 shadow-sm md:p-8 ${className}`}
        >
            {children}
        </section>
    );
}

function BenefitCard({ icon, title, description }) {
    return (
        <div className="rounded-[16px] border border-[#EEF2F8] bg-[#FAFBFE] p-5">
            <span className="text-[28px]" aria-hidden="true">
                {icon}
            </span>
            <h3 className="mt-3 text-[16px] font-semibold text-[#111827] md:text-[17px]">{title}</h3>
            <p className="mt-2 text-[14px] leading-[1.7] text-[#4B5563] md:text-[15px]">{description}</p>
        </div>
    );
}

function ListColumn({ title, items, accent }) {
    return (
        <div className="rounded-[20px] border border-[#EEF2F8] bg-[#FAFBFE] p-6">
            <h3 className={`text-[18px] font-semibold md:text-[20px] ${accent}`}>{title}</h3>
            <ul className="mt-5 space-y-3">
                {items.map((item) => (
                    <li key={item} className="flex items-start gap-3 text-[14px] text-[#374151] md:text-[15px]">
                        <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#0133E9]" />
                        {item}
                    </li>
                ))}
            </ul>
        </div>
    );
}

export default function CompanyWhyChoose() {
    return (
        <div className="space-y-6">
            <SectionCard>
                <p className="text-[13px] font-semibold uppercase tracking-[0.12em] text-[#0133E9]">
                    Why Choose Database Providers?
                </p>
                <h2 className="mt-3 text-[18px] font-regular text-[#111827] md:text-[28px]">
                    Stop Searching. Start Selling.
                </h2>
                <p className="mt-4 max-w-4xl text-[15px] leading-[1.75] text-[#4B5563] md:text-[16px]">
                    Most businesses don&apos;t need access to millions of contacts—they need the right
                    decision-makers for their next campaign. Instead of spending hours searching,
                    filtering, and verifying contacts, simply share your requirements and we&apos;ll
                    deliver a ready-to-use, human-verified database.
                </p>
            </SectionCard>

            <SectionCard>
                <h2 className="text-[18px] font-regular text-[#111827] md:text-[28px]">
                    Why Businesses Choose Us
                </h2>
                <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                    {BENEFITS.map((benefit) => (
                        <BenefitCard key={benefit.title} {...benefit} />
                    ))}
                </div>
            </SectionCard>

            <SectionCard>
                <h2 className="text-[18px] font-regular text-[#111827] md:text-[28px]">
                    Why Buy Custom Data Instead of a Subscription?
                </h2>
                <div className="mt-6 overflow-hidden rounded-[20px] border border-[#EEF2F8]">
                    <div className="grid grid-cols-1 md:grid-cols-2">
                        <div className="border-b border-[#EEF2F8] bg-[#F8FAFC] px-5 py-4 md:border-b-0 md:border-r">
                            <p className="text-[14px] font-semibold text-[#6B7280] md:text-[15px]">
                                Traditional Data Platforms
                            </p>
                        </div>
                        <div className="border-b border-[#EEF2F8] bg-[#0133E9] px-5 py-4">
                            <p className="text-[14px] font-semibold text-white md:text-[15px]">
                                Database Providers
                            </p>
                        </div>
                    </div>
                    {COMPARISON_ROWS.map((row, index) => (
                        <div
                            key={row.traditional}
                            className={`grid grid-cols-1 md:grid-cols-2 ${index < COMPARISON_ROWS.length - 1 ? 'border-b border-[#EEF2F8]' : ''}`}
                        >
                            <div className="border-b border-[#EEF2F8] px-5 py-4 text-[14px] text-[#4B5563] md:border-b-0 md:border-r md:text-[15px]">
                                {row.traditional}
                            </div>
                            <div className="bg-[#F8FAFF] px-5 py-4 text-[14px] font-medium text-[#111827] md:text-[15px]">
                                {row.ours}
                            </div>
                        </div>
                    ))}
                </div>
            </SectionCard>

            <SectionCard>
                <h2 className="text-[18px] font-regular text-[#111827] md:text-[28px]">How It Works</h2>
                <div className="mt-6 grid grid-cols-1 gap-5 md:grid-cols-2">
                    <ListColumn title="You Tell Us:" items={YOU_TELL_US} accent="text-[#111827]" />
                    <ListColumn title="We Deliver:" items={WE_DELIVER} accent="text-[#0133E9]" />
                </div>
            </SectionCard>

            <SectionCard>
                <h2 className="text-[18px] font-regular text-[#111827] md:text-[28px]">Example</h2>
                <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2">
                    {EXAMPLES.map((example) => (
                        <div
                            key={example.question}
                            className="rounded-[16px] border border-[#D6E4FF] bg-[#F8FAFF] p-5"
                        >
                            <p className="text-[15px] font-semibold text-[#0133E9] md:text-[16px]">
                                {example.question}
                            </p>
                            <p className="mt-2 text-[14px] leading-[1.7] text-[#4B5563] md:text-[15px]">
                                {example.answer}
                            </p>
                        </div>
                    ))}
                </div>
            </SectionCard>

            <CompanyMidBanner
                title="You Focus on Closing Deals. We'll Handle the Prospect Research."
                description="Human-Verified • Targeted • Accurate • Fast • Affordable"
                buttonLabel="Get Started"
            />
        </div>
    );
}
